[global]
author=["jlrodriguez"]

[parse]
sourcefile=[ "stfight.cpp" ]

machines=[ "empcity" ]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]

regions = [
    { name="maincpu" },
    { name="audiocpu",            start="JTFRAME_BA1_START" },
    { name="adpcm",               start="ADPCM_START"       },

    { name="stfight_vid:fg_map",  start="FGMAP_START"       },
    { name="stfight_vid:bg_map",  start="BGMAP_START"       },
    { name="stfight_vid:fg_gfx",  start="FGGFX_START"       },
    { name="stfight_vid:bg_gfx",  start="BGGFX_START"       },
    { name="stfight_vid:spr_gfx", start="SPRGFX_START"      },

    { name="mcu",                 start="JTFRAME_PROM_START"},
    { name="stfight_vid:tx_gfx"  },
    { name="stfight_vid:tx_clut" },
    { name="stfight_vid:fg_clut",  sequence=[1,0] },
    { name="stfight_vid:bg_clut",  sequence=[1,0] },
    { name="stfight_vid:spr_clut", sequence=[1,0] },

    { name="proms", skip=true },
    { name="user1", skip=true },
]

order = [
    "maincpu", "audiocpu", "adpcm",
    "stfight_vid:fg_map", "stfight_vid:bg_map",
    "stfight_vid:fg_gfx", "stfight_vid:bg_gfx", "stfight_vid:spr_gfx",
    "mcu", "stfight_vid:tx_gfx", "stfight_vid:tx_clut",
    "stfight_vid:fg_clut", "stfight_vid:bg_clut", "stfight_vid:spr_clut",
]
